package io.wdev.datastructures;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

public class LRUCacheTest {

    @Test public void testSomeLibraryMethod() {
        LRUCache<String, Integer> lru = new LRUCache<>(3);
        lru.put("zero", 0);
        lru.put("one", 1);
        lru.put("two", 2);
        lru.put("three", 3);
        lru.put("four", 4);
        lru.put("five", 5);

        assertNull("LRUCache.get(\"zero\") should return NULL", lru.get("zero"));
        assertNull("LRUCache.get(\"one\") should return NULL", lru.get("one"));
        assertNull("LRUCache.get(\"two\") should return NULL", lru.get("two"));
        assertEquals("LRUCache.get(\"three\") should return 3", Integer.valueOf(3), lru.get("three"));
        assertEquals("LRUCache.get(\"four\") should return 4", Integer.valueOf(4), lru.get("four"));
        assertEquals("LRUCache.get(\"five\") should return 5", Integer.valueOf(5), lru.get("five"));
    }
}
