package io.wdev.datastructures;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import static org.junit.Assert.assertTrue;

public class RandomizedListTest {
    @Test
    public void testSomeLibraryMethod() {
        RandomizedListTest classUnderTest = new RandomizedListTest();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
